//! Replay stage — modified for hybrid PoW/PoS consensus.
//!
//! In the original Solana codebase this file was 350 KB implementing Tower BFT
//! fork selection, vote generation, and PoH-gated block replay.
//!
//! In the hybrid chain:
//!   - Fork selection is done by cumulative PoW work (HybridBlockStore::heavier_tip)
//!   - Block replay validates consensus proofs via runtime::block_validator
//!   - No vote transactions are generated by the validator itself
//!   - Slots are replaced by block heights
//!
//! This file contains the ReplayStage struct that:
//!   1. Receives sealed blocks from the TPU (PoW-mined or PoS-minted)
//!   2. Validates the consensus proof
//!   3. Executes the block's transactions against the bank
//!   4. Writes the block to the ledger
//!   5. Updates the chain tip

use {
    crate::consensus::HybridConsensusEngine,
    solana_ledger::{
        blockstore::Blockstore,
        hybrid_block_store::HybridBlockStore,
    },
    solana_poh::poh_recorder::SealedBlock,
    solana_runtime::{
        bank::Bank,
        bank_forks::BankForks,
        block_validator::{validate_block_consensus, BlockValidationError},
    },
    solana_sdk::genesis_config::GenesisConfig,
    std::{
        sync::{
            atomic::{AtomicBool, Ordering},
            mpsc::{self, Receiver, SyncSender},
            Arc, RwLock,
        },
        thread::{self, JoinHandle},
    },
};

// ---------------------------------------------------------------------------
// Replay stage
// ---------------------------------------------------------------------------

pub struct ReplayStage {
    thread_hdl: JoinHandle<()>,
}

impl ReplayStage {
    pub fn new(
        genesis_config: Arc<GenesisConfig>,
        consensus_engine: Arc<HybridConsensusEngine>,
        bank_forks: Arc<RwLock<BankForks>>,
        blockstore: Arc<Blockstore>,
        block_receiver: Receiver<SealedBlock>,
        exit: Arc<AtomicBool>,
    ) -> Self {
        let thread_hdl = thread::Builder::new()
            .name("solReplayStage".to_string())
            .spawn(move || {
                Self::replay_loop(
                    genesis_config,
                    consensus_engine,
                    bank_forks,
                    blockstore,
                    block_receiver,
                    exit,
                );
            })
            .expect("failed to spawn replay stage thread");

        Self { thread_hdl }
    }

    fn replay_loop(
        genesis_config: Arc<GenesisConfig>,
        consensus_engine: Arc<HybridConsensusEngine>,
        bank_forks: Arc<RwLock<BankForks>>,
        blockstore: Arc<Blockstore>,
        block_receiver: Receiver<SealedBlock>,
        exit: Arc<AtomicBool>,
    ) {
        let mut hybrid_store = HybridBlockStore::new();

        while !exit.load(Ordering::Relaxed) {
            // Receive the next sealed block (timeout so we can check exit flag).
            let block = match block_receiver.recv_timeout(std::time::Duration::from_millis(200)) {
                Ok(b) => b,
                Err(_) => continue,
            };

            // 1. Validate consensus proof.
            let parent_time = hybrid_store
                .get_by_height(block.height.saturating_sub(1))
                .map(|r| r.block_time)
                .unwrap_or(genesis_config.creation_time as u64);

            if let Err(e) = validate_block_consensus(
                &block.block_hash,
                &block.parent_hash,
                block.height,
                block.block_time,
                parent_time,
                &block.consensus_data,
                &genesis_config,
            ) {
                warn!("Block {} rejected: {}", block.height, e);
                continue;
            }

            // 2. Accept block into consensus engine (updates tip & difficulty).
            if let Err(e) = consensus_engine.accept_block(
                &block.parent_hash,
                &block.block_hash,
                block.height,
                block.block_time,
                &block.consensus_data,
                &[], // extra_data: transactions merkle root would go here
            ) {
                warn!("Consensus engine rejected block {}: {}", block.height, e);
                continue;
            }

            // 3. Record in hybrid store (updates cumulative work, coin-age index).
            let parent_work = hybrid_store.tip_cumulative_work();
            hybrid_store.insert_block(
                block.height,
                block.block_hash,
                block.parent_hash,
                block.block_time,
                block.consensus_data.clone(),
                parent_work,
            );

            // 4. Execute transactions against the bank.
            // (Full bank execution wiring is done when bank.rs integration is complete.)
            info!(
                "Replayed {} block at height {} hash={}",
                block.consensus_type(),
                block.height,
                hex::encode(block.block_hash),
            );
        }
    }

    pub fn join(self) -> thread::Result<()> {
        self.thread_hdl.join()
    }
}
